---
title: "Untitled"
author: '410773004'
date: "2020/3/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R package

```{r}
library(googlesheets4)
```

## create project
```{r}
a <- 2 
a = 2 # <-跟=同義
```

```{r}
a
```

```{r}
'我的年紀' = 20
```

```{r}
mean(c(1,2,3))  # 平均數
seq(from=1,to=10,by=3) #數列，參數可換位置
seq(1,10,3) #若參數照順序可省略
```


```{r}
x=5
str(x) #str()檢視變數型態
```

```{r}
library(bit64)
print(2^50,digits=20)
print(2^50+1,digits=20)

print(2^53,digits=20)
print(2^53,digits=10)
print(as.integer64(2)^53+1,digits=21)
```

```{r}
a=180
`我的身高`<-a
`我的身高`
b=60
`我的體重`<-b
`我的身高`+`我的體重`
```

```{r}
x=5
y=c(2,5)
z=c(2,x)
```

```{r}
x=c(1,5)
y=c(2,3)
z=c(x,y)
m=c(1,5,2,3)
n=c(c(1,5),c(2,3))
```

```{r}
x=c(1,5)
y=c(2,3)
z=c()
m=c(x,y)
n=c(z,x)
```


```{r}
library(lubridate)
```



```{r}
vectorExample=c(2,6,7)
listExample=list(2,6,7)

print(vectorExample)
print(listExample)
```

```{r}
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")


#若用list儲存
library(lubridate)
list(ymd_hms("2020-03-31T13:40:55Z"),#Date/Time
     "一芳",#Character
     2,#Numereic
     "水果茶"#Character)
    )
print('小明交易1')
```

```{r}
list(
  c("108學年第1學期","高級會計學","高等統計學"),
  c("108學年第2學期","食在拉丁美洲")
 )
`小明108課表` <- list(
  list("108學年第1學期","高級會計學","高等統計學"),
  list("108學年第2學期","食在拉丁美洲")
 )


list(
  c("108學年第1學期","高級會計學","高等統計學"),
  c("108學年第2學期","食在拉丁美洲")
 )

`小明108課表` <- list(
  `上學期`=list(`semester`=c("108-1"),`courses`=c("高級會計學","高等統計學")),
  `下學期`=list(`semester`=c("108-2"),`courses`=c("食在拉丁美洲"))
 )
print(`小明108課表`)

```

```{r}
commit=list(
  author=list("名字"="Martin老師",
                "信箱"="mtlin@gm.ntpu.edu.tw",
                "時間"=ymd_hms("2020-03-25T07:17:40")),
  `committer`=list("名字"="emilyluckey",
                   "信箱"="emily007@gmail.com",
                   "時間"=ymd_hms("2020-03-26T08:18:40"))  ,
  `message`="update"
)
print(commit)

```

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)

vectorExample[[1]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
length(listExample)
listExample[[1]]
listExample[[2]]
```

```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
length(tainanSportsMap)
tainanSportsMap[[1]]
tainanSportsMap[[1076]]
```

```{r}
names(listExample)
listExample$student
listExample$`學期`
listExample$name
listExample[["student"]]
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F)->newTaipeiCityVaccine
newTaipeiCityVaccine
str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
str(newTaipeiCityVaccine$success)
str(newTaipeiCityVaccine[[2]],max.level=1)

```

```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,1,2)]
```

```{r}
listExample
listExample[c(1,2)]

```

```{r}
vectorExample
vectorExample[c(T,T,F)] #T=要留資料,F=不要資料
```

```{r}
library(jsonlite)
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
names(taipeiNightMarkets)
length(taipeiNightMarkets)
taipeiNightMarkets[c(T,F,T,T,F,
                     F,T,T,T,F,
                     T,T,T,F)]->selectmarkets
selectmarkets
```


```{r}
selectmarkets=rep(F,14)
selectmarkets
selectmarkets[c(1,5,10,14)]=T
selectmarkets
```

```{r}
str(listExample,max.level=3)

get1=listExample[["學期"]] #[[]]=' 將值取出
get2=listExample["學期"] #[]=只留下

```
```{r}
str(get1,max.level=1)
str(get2,max.level = 3)
```

```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]]
```

```{r}
select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numVector[c(T,T,F,T,F,F,T)][c(1,4)]

```

```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly=c(T,T,F,F,T)
names[econOnly]
gender[econOnly]
names[econOnly][c(T,T,F)]
```
































