---
title: "Untitled"
author: '410773004'
date: "2020/3/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R package

```{r}
library(googlesheets4)
```

## create project
```{r}
a <- 2 
a = 2 # <-跟=同義
```

```{r}
a
```

```{r}
'我的年紀' = 20
```

```{r}
mean(c(1,2,3))  # 平均數
seq(from=1,to=10,by=3) #數列，參數可換位置
seq(1,10,3) #若參數照順序可省略
```


```{r}
x=5
str(x) #str()檢視變數型態
```

```{r}
library(bit64)
print(2^50,digits=20)
print(2^50+1,digits=20)

print(2^53,digits=20)
print(2^53,digits=10)
print(as.integer64(2)^53+1,digits=21)
```

```{r}
a=180
`我的身高`<-a
`我的身高`
b=60
`我的體重`<-b
`我的身高`+`我的體重`
```

```{r}
x=5
y=c(2,5)
z=c(2,x)
```

```{r}
x=c(1,5)
y=c(2,3)
z=c(x,y)
m=c(1,5,2,3)
n=c(c(1,5),c(2,3))
```

```{r}
x=c(1,5)
y=c(2,3)
z=c()
m=c(x,y)
n=c(z,x)
```


```{r}
library(lubridate)
```



```{r}
vectorExample=c(2,6,7)
listExample=list(2,6,7)

print(vectorExample)
print(listExample)
```

```{r}
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")


#若用list儲存
library(lubridate)
list(ymd_hms("2020-03-31T13:40:55Z"),#Date/Time
     "一芳",#Character
     2,#Numereic
     "水果茶"#Character)
    )
print('小明交易1')
```

```{r}
list(
  c("108學年第1學期","高級會計學","高等統計學"),
  c("108學年第2學期","食在拉丁美洲")
 )
`小明108課表` <- list(
  list("108學年第1學期","高級會計學","高等統計學"),
  list("108學年第2學期","食在拉丁美洲")
 )


list(
  c("108學年第1學期","高級會計學","高等統計學"),
  c("108學年第2學期","食在拉丁美洲")
 )

`小明108課表` <- list(
  `上學期`=list(`semester`=c("108-1"),`courses`=c("高級會計學","高等統計學")),
  `下學期`=list(`semester`=c("108-2"),`courses`=c("食在拉丁美洲"))
 )
print(`小明108課表`)

```

```{r}
commit=list(
  author=list("名字"="Martin老師",
                "信箱"="mtlin@gm.ntpu.edu.tw",
                "時間"=ymd_hms("2020-03-25T07:17:40")),
  `committer`=list("名字"="emilyluckey",
                   "信箱"="emily007@gmail.com",
                   "時間"=ymd_hms("2020-03-26T08:18:40"))  ,
  `message`="update"
)
print(commit)

```

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)

vectorExample[[1]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
length(listExample)
listExample[[1]]
listExample[[2]]
```

```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
length(tainanSportsMap)
tainanSportsMap[[1]]
tainanSportsMap[[1076]]
```

```{r}
names(listExample)
listExample$student
listExample$`學期`
listExample$name
listExample[["student"]]
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F)->newTaipeiCityVaccine
newTaipeiCityVaccine
str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
str(newTaipeiCityVaccine$success)
str(newTaipeiCityVaccine[[2]],max.level=1)

```

```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,1,2)]
```

```{r}
listExample
listExample[c(1,2)]

```

```{r}
vectorExample
vectorExample[c(T,T,F)] #T=要留資料,F=不要資料
```

```{r}
str(listExample)
listExample[[2]][[1]][[1]][[2]]
```


```{r}
today <- list(
  list("台北市",highest_temp=c(highest_temp = 25),
                lowest_temp=c(lowest_temp = 18)),
  list("新北市",highest_temp=c(highest_temp = 24),lowest_temp=c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",highest_temp =c(highest_temp = 25),lowest_temp=c(lowest_temp = 18)),
  list("新北市",highest_temp =c(highest_temp = 24),lowest_temp=c(lowest_temp = 15)))

weather <- list(today,tomorrow)

str(weather)

```

```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp # 明天/新北市/highest_temp

```


```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
a[[7]]="Johnson"
a=c(a,"Mary")
a
```


```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
list1[[1]][[2]]=ymd("1997-03-21")

list1[[2]]=list(name="Mary",
              birthday=ymd("1998-08-24")
              )
str(list1)

```


```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)


```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)


```

```{r}
a
a[-c(1,3)]

```

```{r}
str(list1)
list1[[1]]=list1[[1]][-3]
list1
```

```{r}
str(list1)
list1[[2]][c(1,2)]=NULL
list1


```


```{r}
a <- c(2, 3, 5)
b <- c(4,-1, 3)


a+b
a-b
a*b
a/b

a %% b
# 相當於
c(2%%4, 3%%(-1), 5%%3)

a ** b

5*c(1,3,4)+7
# 其實是
c(5)*c(1,3,4)+c(7)

## 對向量5，向量7進行recycle:
c(5,5,5)*c(1,3,4)+c(7,7,7)
## Recycle等長後才進行elementwise operation:
c(5*1+7, 5*3+7, 5*4+7)
```

```{r}
# 狀況一: 堆疊一定倍數剛好一樣長
c(2,3)/c(-2,-13,10,22)
c(2,3,2,3)/c(-2,-13,10,22)

```

```{r}
# 狀況二: 倍數堆疊一定會超過，只好截斷
c(2,3)/c(-2,-13,10)
c(2,3,2)/c(-2,-13,10)

```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
example$name[c(T, F, T, F)]


str(example[c("name","height")])


pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]

```

```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
str(transcript100to103)
# 各學屆2年級人數
table(transcript100to103$學屆)

# 只要成績大於85的
pick_above85 <-
  transcript100to103$`成績` > 85

# 各學屆2年級成績大於85年數
table(transcript100to103$學屆[pick_above85])

```


```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)



print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```

```{r}
source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")
str(exchangeRate)

# 只要1998年1月（含）以後的
library(lubridate)
pick_after98_01 <-
  exchangeRate$期間 >= ymd("1998-01-01")

exchangeRate_after98 <-
  list(
    `期間`=exchangeRate$`期間`[pick_after98_01],
    `幣別`=exchangeRate$`幣別`[pick_after98_01],
    `匯率`=exchangeRate$`匯率`[pick_after98_01]
    
  )


```

```{r}
print(example[c("name","allowance")])


example$allowance<-ordered(example$allowance)

pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]

```

```{r}
example$allowance=
  factor(c("0-1000","1001-2000","2000+"),
         levels=c("0-1000","1001-2000","2000+"),
         ordered=T)#設定為可排序


```

```{r}
print(example[c("name","bloodType")])

pick_bloodB <- example$bloodType == "B"
example$name[pick_bloodB]

```

```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)

pick_evens <- (sequenceNums %% 2) == 0
sequenceNums[pick_evens]

```
```{r}
x <- c(1,5,8)
y <- c(5,8)

# x裡的元素值是不是屬於y集合
x %in% y

```

```{r}
print(example[c("name","residence")])

set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- example$residence %in% set_TaipeiMetro
example$name[pick_fromTaipeiMetro]

```

```{r}
str(transcript100to103)
set_LAWBusiness=c("法學院","商學院" )
pick_LAWBuisiness=transcript100to103$學院%in%set_LAWBusiness
table(pick_LAWBuisiness)
```

```{r}
levels(factor(transcript100to103$學院))

unique(transcript100to103$學院)
```

```{r}
pick_not_fromTaipeiMetro=!pick_fromTaipeiMetro
pick_not_fromTaipeiMetro
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

is.na(x2)
```

```{r}
print(example[c("name","weight")])

pick_na <- is.na(example$weight)
example$name[pick_na]

```

```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")
example$name[pick_loveFood]
```

```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/od/data/api/EDC3AD26-8AE7-4916-A00B-BC6048D19BF8?$format=json") ->
  garbageRoutes
garbageRoutes$linename=factor(garbageRoutes$linename)
levels(garbageRoutes$linename)
library(stringr)
str_detect(garbageRoutes$linename,"下午")
```

```{r}
fruit <- c("apple", "banana", "pear", "pinapple")
str_detect(fruit, "a")
str_detect(fruit, "^a") #a開頭
str_detect(fruit, "a$") #a結尾
str_detect(fruit, "b")
str_detect(fruit, "[aeiou]")

# Also vectorised over pattern
str_detect("aecfg", letters)

# Returns TRUE if the pattern do NOT match
str_detect(fruit, "^p", negate = TRUE) #negate=TRUE->反向的意思

```























